#!/bin/bash

RELEASE_DIR=../releases
RELESE_DIR_ANDROID=$RELEASE_DIR/android
RELEASE_HTML_DIR=$RELEASE_DIR
RELESE_DIR_IOS=$RELEASE_DIR/ios
IOS_BUILD_DIR=ios/axemas

#Release repository cleanup fase

if ! [ -d $EXAMPLES_REPO ]; then
    echo Cloning Examples Repo
    mkdir $RELEASE_DIR
    git clone https://github.com/AXEMAS/releases.git $EXAMPLES_REPO 
fi

rm -R $RELEASE_DIR/android
rm -R $RELEASE_DIR/html
rm -R $RELEASE_DIR/ios
mkdir $RELEASE_DIR/android
mkdir $RELEASE_DIR/html
mkdir $RELEASE_DIR/ios
echo Cleaning up release directory

#iOS build & clone
echo Starting iOS project update

cd $IOS_BUILD_DIR
./build_libaxemas
cd ../../
cp -r ios/axemas/release $RELESE_DIR_IOS
echo Finished iOS project update

#Android build & clone
echo Starting Android project update

cd android
./gradlew clean && ./gradlew assemble
cp app/build/outputs/aar/app-release.aar ../$RELESE_DIR_ANDROID/axemas.aar
echo Finished Android project update

#HTML clone
echo Starting HTML library update
cd ..

cp -r html $RELEASE_HTML_DIR
echo Finished HTML library update
echo Release \hg st
done, don\'t forget to commit and tag new version
